### ISSUE TITLE
can't log in on windows machine

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/BowlerBuilder#1]
https://hastebin.com/apayodonaf.bash
https://hastebin.com/eyumunowub.bash

**Comment by madhephaestus** [comment]
Is the asset repo fully cloned before that window is opened?

**Comment by Octogonapus** [comment]
I don't know. Honestly I just opened this for myself so I could get the log files off the machine. I am going to look later tonight.

**Comment by Octogonapus** [comment]
No problems with this recently. BB now tries to clone the asset repo when it opens just in case.
