### ISSUE TITLE
Repository grouping by project

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/BowlerBuilder#16]
The Git > My Repositories menus should be grouped by project. The same repo can appear in different project.

**Comment by Octogonapus** [comment]
@madhephaestus Can you specify what you meant by "project"?

**Comment by madhephaestus** [comment]
I have forks of projects in different groups, and this results in duplicate repo entries in the repository list. It might be easy enough for you to just prepend the group name to the repo name. when i run bowler builder i get lots of duplicates.
