### ISSUE TITLE
Script tab needs more script layers

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/BowlerBuilder#19]
There are more layers of scripts that need to be editable.

**Comment by Octogonapus** [comment]
@madhephaestus Can you specify what objects have scripts we can't currently edit? You can edit the cad/walking engines, and the cad/dh engines for each limb.

**Comment by madhephaestus** [comment]
yeah, thats it. Just checked the latest build and its all there.

**Comment by Octogonapus** [comment]
Ok. If you think we have what we need, please close the issue.
