### ISSUE TITLE
Application should run if preloading network assets is slow

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/BowlerBuilder#22]
If internet connectivity is not present or is slow, the application should still load normally.

**Comment by Octogonapus** [comment]
@madhephaestus When you ran into this issue, did BowlerBuilder actually load (just slowly)? I'm thinking about just throwing the preloading on another thread, but I don't know if the ScriptingEngine can handle that. Do you know?

**Comment by madhephaestus** [comment]
I disabled network and attempted to open the application. it failed to launch.

**Comment by Octogonapus** [comment]
Closing because this is related to JavaUI, which is being removed.
