### ISSUE TITLE
Add a way to copy Git URL

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/BowlerBuilder#28]
Default copy Git URL behavior should copy a string that is the arguments to run the script. There should also be an option to copy the push URL.

**Comment by Octogonapus** [comment]
@madhephaestus Can you clarify what you meant by "15) Copy gist URL should make the string pair of as the arguments would be pasted in a script run"?

**Comment by madhephaestus** [comment]
so when i hit the button i would like to get the literal of 
`
 "https://github.com/keionbis/SmallKat.git","launch.groovy"
`
as the content of the clipboard.

**Comment by Octogonapus** [comment]
Closing because this is related to JavaUI, which is being removed.
